### ISSUE TITLE
No output from test files

### ISSUE THREAD

**Issue by alexbacita** [BGI-Qingdao/Circle-Map-cpp#1]
Greetings, 

When implementing the pipeline on the test files provided there are 2 errors that stand out:
- coverage.tsv not found
- database not having enough columns

Please see the full output below. Any help is much appreciated

method-dev@GenomeDellCoder:/mnt/c/UserData/test$ circle_map++ Realign -i sort_circular_read_candidates.bam -qbam qname_u
nknown_circle.bam -sbam sorted_unknown_circle.bam -fasta hg38.fa -o my_unknown_circle.bed
2024-03-06 11:09:03: start candidate_intervals

sh: 1: megadepth: not found
awk: fatal: cannot open file `/mnt/c/UserData/test/temp_2719/sort_candidate_bam.coverage.tsv' for reading: No such file or directory

*****
***** ERROR: Requested column 4, but database file - only has fields 1 - 0.
estimated insert size mean=298.57598499061913, std=23.951019931040737
2024-03-06 11:09:03: start realign_cm

[I::load_peaks] peaks.bed intervals : 0
[I::load_peaks] chunked candidate intervals : 0
[I::load_mates_sa_sr] total mate intervals : 27
[I::main] merging data...
[I::main] merging data end...
[I::main] start realign softclip read, this may take a long time...
[I::main] realign softclip end...
[I::main] all done...
2024-03-06 11:10:27: start megadepth

sh: 1: megadepth: not found
2024-03-06 11:10:27: merge result

load /mnt/c/UserData/test/temp_2719/ecctemp.txt
load fai of hg38.fa
load /mnt/c/UserData/test/temp_2719/sort_bam.coverage.tsv
coverage not exist ! exit ...
2024-03-06 11:10:29: Realign all done

**Comment by cchd0001** [comment]
Hi, please make sure megadepth is working

**Comment by alexbacita** [comment]
Great, that solved it, thanks! Would be good to have it added to 'Dependencies' it seems
